language: go
go:
  - 1.7
  - tip

sudo: false

before_install:
  - go get github.com/golang/lint/golint
  - go get github.com/vbatts/git-validation

install: true

script:
  - go vet -x $(go list ./... | grep -v vendor)
  - $HOME/gopath/bin/golint ./... | grep -v vendor
  - $HOME/gopath/bin/git-validation -run DCO,short-subject -v -range ${TRAVIS_COMMIT_RANGE}
  - go build
  - go test -v $(go list ./... | grep -v /vendor/)
